### ISSUE TITLE
Speed and amount of targets 

### ISSUE THREAD

**Issue by dimabuko** [visionargmbh/Visionar-iOS#1]
Hello,
 
now I'm in the middle of my project with augmented reality targets in the book project: at the moment 137 targets were added. Now when I'm adding every next targets it seems for me that the speed of recognition of targets dramatically decreases. Some targets are working just fine, some of them are incredibly slow and it's very difficult to make them work.
 
I made short video to show you what do I mean:
https://www.dropbox.com/s/2p47s6dktx41n2h/RPReplay_Final1592569498.MOV?dl=0
 
1) is something wrong with this specific image?
 
2) do I need to prepare my images for targets in specific sizes/resolution, tinyfy them or something like that? At the moment I make them 2400px wide and export for web using 80% jpeg progressive compression in Adobe Ps. Is it fine?
 
3) or is it fine and it's a limitation of used technology... Or something with my phone... please if any detailed explanation could be provided here, let me know to understand how to make my book + app incredibly fast working.
 
Dmitry.

**Comment by dimabuko** [comment]
Hello again,
 
so I used second "demo" app available in Visionar Studio to test the issue myself. Test shows that if in the app there is only one target - it works fast and awesome. If the app has 137 targets inside it works incredibly slow. It doesn't matter if I use your Visionar App or my app created using your sdk.
 
1) 1 target, visionar app: https://www.dropbox.com/s/u6un9jqc7zie6u9/visionar-app-1target.MP4?dl=0
2) 137 targets, visionar app: https://www.dropbox.com/s/85exhgbhgv55egw/visionar-app-137targets.MP4?dl=0
3) 137 targets, "Pralinarium" app: https://www.dropbox.com/s/hqmw9ylbk9fpt8x/sdk-app-137targets.MP4?dl=0 
 
From that moment I understand that if I go further - with every added target my app would getting slower and slower. I was thinking that I need about 300–400 targets to complete the whole book + ar app project. Now it's not even the half added. Please advise, I'm looking for any solution. I was planning to finish the project and move to print stage and print initial book samples in the end of next week, but this problem has critical priority and I can't move on.
 
Dmitry.

**Comment by dimabuko** [comment]
I believe it's okay to submit an issue here? Because I haven't received any responses to my last requests using "support@visionar.com"

**Comment by visionargmbh** [comment]
We fixed this in v1.1.
